version: 1.7-b{build}
# version: 0.6-latest
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  # - x64
init:
- cmd: echo %cd%
- cmd: curl -L -o %temp%\add_gitutf16.py https://raw.githubusercontent.com/rexdf/CommandTrayHost/master/add_gitutf16.py
- cmd: C:\Python36\python.exe %temp%\add_gitutf16.py
# clone_depth: 1
clone_folder: c:\projects\CommandTrayHost
install:
- cmd: >-
    vcpkg install rapidjson rapidjson:x64-windows nlohmann-json nlohmann-json:x64-windows

    C:\Python36\python.exe vcpkg_patch.py
before_build:
    # - cmd: cd c:\projects\CommandTrayHost
    - cmd: >-
        C:\Python36\Scripts\pip.exe install chardet pytz

        C:\Python36\python.exe version_set.py %APPVEYOR_BUILD_NUMBER% 1 7 4
build:
  project: c:\projects\CommandTrayHost\CommandTrayHost.sln
  verbosity: minimal
after_build:
- cmd: msbuild "c:\projects\CommandTrayHost\CommandTrayHost.sln" /verbosity:minimal /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild "c:\projects\CommandTrayHost\CommandTrayHost.sln" /verbosity:minimal /p:Configuration=XP-Release /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# - cmd: cd c:\projects\CommandTrayHost
- cmd: >-
    mkdir CommandTrayHost-x64

    mkdir CommandTrayHost-x86

    mkdir CommandTrayHost-xp-x86

    copy x64\Release\CommandTrayHost.exe CommandTrayHost-x64\

    copy Release\CommandTrayHost.exe CommandTrayHost-x86\

    copy XP-Release\CommandTrayHost.exe CommandTrayHost-xp-x86\

    curl -L -o upx.zip https://github.com/upx/upx/releases/download/v3.94/upx394w.zip

    7z e upx.zip *.exe -r

    upx CommandTrayHost-x64\CommandTrayHost.exe

    upx CommandTrayHost-x86\CommandTrayHost.exe

    upx CommandTrayHost-xp-x86\CommandTrayHost.exe

    7z a -tzip CommandTrayHost-%APPVEYOR_BUILD_VERSION%.zip .\CommandTrayHost-x64\ .\CommandTrayHost-x86\ .\CommandTrayHost-xp-x86\
artifacts:
- path: CommandTrayHost-%APPVEYOR_BUILD_VERSION%.zip
  name: CommandTrayHost

deploy:
  release: $(appveyor_build_version)
  description: 'nightly'
  provider: GitHub
  auth_token:
    secure: 6BqGKqbQbDfnZ3Y7SHvdQkPVCjXcJ1GIgPe41oD8K7ttPY/ivWN3iMyq2eZ1s4RD # your encrypted token from GitHub
  artifact: CommandTrayHost            # upload all NuGet packages to release assets
  prerelease: true
  force_update: true
  on:
    branch: release
    appveyor_repo_tag: false        # deploy on tag push only

cache: c:\tools\vcpkg\installed\  -> vcpkg_cache.txt
